version: 2
jobs:
  unittest:
    docker:
      - image: circleci/node:16.10.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

workflows:
  version: 2
  test_unittest:
    jobs:
      - unittest
